### ISSUE TITLE
Dyn - Domain with just NS records crashes with "'NoneType' object has no attribute 'desired'"

### ISSUE THREAD

**Issue by timhughes** [github/octodns#122]
This is the stacktrace with ipaddress and domain numbers changed

```
thughes@titanium [0] $ octodns-dump --config-file config/production.yaml 123.123.123.IN-ADDR.ARPA. dyn --output-dir domains
2017-10-13T17:47:58  [140371146815232] INFO  Manager __init__: config_file=config/production.yaml
2017-10-13T17:47:58  [140371146815232] INFO  Manager __init__:   max_workers=1
2017-10-13T17:47:58  [140371146815232] INFO  Manager __init__:   max_workers=False
2017-10-13T17:47:58  [140371146815232] INFO  Manager dump: zone=123.123.123.IN-ADDR.ARPA., sources=()
2017-10-13T17:48:02  [140371146815232] INFO  DynProvider[dyn] populate:   found 1 records
2017-10-13T17:48:02  [140371146815232] INFO  YamlProvider[dump] plan: desired=123.123.123.in-addr.arpa.
2017-10-13T17:48:02  [140371146815232] INFO  YamlProvider[dump] plan:   No changes
2017-10-13T17:48:02  [140371146815232] INFO  YamlProvider[dump] apply: making changes
Traceback (most recent call last):
  File "/home/thughes/git/example/example_dns_octodns/venv/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/home/thughes/git/example/example_dns_octodns/venv/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/home/thughes/git/example/example_dns_octodns/venv/lib/python2.7/site-packages/octodns/manager.py", line 365, in dump
    target.apply(plan)
  File "/home/thughes/git/example/example_dns_octodns/venv/lib/python2.7/site-packages/octodns/provider/base.py", line 143, in apply
    self._apply(plan)
  File "/home/thughes/git/example/example_dns_octodns/venv/lib/python2.7/site-packages/octodns/provider/yaml.py", line 76, in _apply
    desired = plan.desired
AttributeError: 'NoneType' object has no attribute 'desired'
```

This is the exported zonefile with ipaddress changed

```
$ORIGIN 123.123.123.IN-ADDR.ARPA.
@                      3600 SOA   ns1.p23.dynect.net. (
                              it.example.com.            ; address of responsible party
                              1                          ; serial number
                              3600                       ; refresh period
                              600                        ; retry period
                              604800                     ; expire time
                              1800                     ) ; minimum ttl
                      86400 NS    ns1.p23.dynect.net.
                      86400 NS    ns2.p23.dynect.net.
                      86400 NS    ns3.p23.dynect.net.
                      86400 NS    ns4.p23.dynect.net.
                      
```

**Comment by timhughes** [comment]
Adding in a TXT record makes it work correctly

```
$ORIGIN 164.34.185.IN-ADDR.ARPA.
@                      3600 SOA   ns1.p23.dynect.net. (
                              it.lmax.com.               ; address of responsible party
                              2                          ; serial number
                              3600                       ; refresh period
                              600                        ; retry period
                              604800                     ; expire time
                              1800                     ) ; minimum ttl
                      86400 NS    ns1.p23.dynect.net.
                      86400 NS    ns2.p23.dynect.net.
                      86400 NS    ns3.p23.dynect.net.
                      86400 NS    ns4.p23.dynect.net.
foo                    3600 TXT   "qwerty"
```

**Comment by ross** [comment]
I can confirm this issue. There's nothing specific to Dyn about it. It's an edge case when trying to dump a zone with no records. (Root NS records are ignored currently, /cc https://github.com/github/octodns/pull/53).

I'll try and come up with a reasonable solution for this case shortly. If you need a work around the resulting file would just be:

```yaml
---
```

😁
