### ISSUE TITLE
Problems with Cloudflare updates

### ISSUE THREAD

**Issue by jr-RXcode** [github/octodns#144]
I'm trying to update a cloudflare record and I get the following error. I'm using the latest version of octodns, also I'm able to create a new record but not update it. Any suggestions ? 

2017-11-08T10:57:40  [140203730163520] INFO  CloudflareProvider[cloudflare] apply: making changes
Traceback (most recent call last):
  File "octodns/env/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "octodns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 313, in sync
    total_changes += target.apply(plan)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/base.py", line 157, in apply
    self._apply(plan)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 285, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 252, in _apply_Update
    self._apply_Create(change)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 248, in _apply_Create
    self._request('POST', path, data=content)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 68, in _request
    resp.raise_for_status()
  File octodns/env/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/3043340984359 tj04944242/dns_records

**Comment by ross** [comment]
Not something I've seen before outside of when I was developing the provider. My guess would be that it's a case of where they have unexpected restrictions on a record type. Will need more to have a shot at figuring out what's up. Can you share what record it's trying to update there? The output of a the noop and/or the bit just before the error message when run with --debug might have useful info. Otherwise it'd probably require hacking on the code a bit to print out the `resp.content` just before `resp.raise_for_status()`.

**Comment by jr-RXcode** [comment]
created a test CNAME record like the following 
 my-test:
   ttl:300
   type: CNAME
   value: assets.mydomain.com.
after I synced it to cloudflare I confirmed that the record was created.  My next step was to update the record using octodns. I updated my zone file by changing the ttl from 300 to 600 and then tried to update it using octodns, that's where I get the error. Here is the error using debug mode.

2017-11-08T14:54:59  [140602756200256] DEBUG Manager sync:   checking safety
2017-11-08T14:54:59  [140602756200256] DEBUG Manager sync:   applying
2017-11-08T14:54:59  [140602756200256] INFO  CloudflareProvider[cloudflare] apply: making changes
2017-11-08T14:54:59  [140602756200256] DEBUG CloudflareProvider[cloudflare] _apply: zone=mydomain.com., len(changes)=1
2017-11-08T14:54:59  [140602756200256] DEBUG CloudflareProvider[cloudflare] _request: method=POST, path=/zones/a3457666654gfsdgsdfsg4546f/dns_records
2017-11-08T14:54:59  [140602756200256] DEBUG urllib3.connectionpool https://api.cloudflare.com:443 "POST /client/v4/zones/a3457666654gfsdgsdfsg4546f/dns_records HTTP/1.1" 400 None
2017-11-08T14:54:59  [140602756200256] DEBUG CloudflareProvider[cloudflare] _request:   status=400
Traceback (most recent call last):
  File "octodns/env/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "octodns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 313, in sync
    total_changes += target.apply(plan)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/base.py", line 157, in apply
    self._apply(plan)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 285, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 252, in _apply_Update
    self._apply_Create(change)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 248, in _apply_Create
    self._request('POST', path, data=content)
  File "octodns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 68, in _request
    resp.raise_for_status()
  File "octodns/env/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/a3457666654gfsdgsdfsg4546f/dns_records

**Comment by ross** [comment]
Hrm. Looks like an issue with create before delete. That could be flipped, but that'd be dangerous. Their api seems to support update, https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record, but switching to that will require a bit of work so won't be a quick fix.

**Comment by NicolaiSchmid** [comment]
I actually have the same issue, I've set the debug flag, but I can't narrow it down to a specific record, which causes the error, let me know, if I can help by providing more logs

**Comment by ross** [comment]
WIP PR to address this issue in https://github.com/github/octodns/pull/162. Turned out to be a lot more involved than I'd hoped :frowning_face:. Run out of time for it today so will have to return to it and more thoroughly test things in when I get a chance (before that can merge.)

**Comment by jasonkuehl** [comment]
Having the same issue but seeing how old this issue can it be assumed CF is not supported?

`2020-05-07T17:06:38  [140275515098880] DEBUG CloudflareProvider[cloudflare] _request:   status=400
Traceback (most recent call last):
  File "/home/yolocolo/dns-control/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/manager.py", line 315, in sync
    plans = [p for f in futures for p in f.result()]
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/manager.py", line 243, in _populate_and_plan
    plan = target.plan(zone)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/provider/base.py", line 51, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 261, in populate
    records = self.zone_records(zone)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 214, in zone_records
    zone_id = self.zones.get(zone.name, False)
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 114, in zones
    resp = self._request('GET', '/zones', params={'page': page})
  File "/home/yolocolo/dns-control/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 101, in _request
    raise CloudflareError(resp.json())
octodns.provider.cloudflare.CloudflareError: Invalid request headers
`

**Comment by NicolaiSchmid** [comment]
@jasonkuehl Have you been able to resolve your issue?

**Comment by NicolaiSchmid** [comment]
I was actually able to resolve my issue. I had passed both email and token, which was "too much". Just passing the token resolved the issue
