### ISSUE TITLE
[cloudflare] octodns-dump doesn't like MX records with 0 Priority

### ISSUE THREAD

**Issue by bcruik** [github/octodns#172]
It looks like octodns does not like to export records from cloudflare with a 0 priority.

Changing the records in Cloudflare from 0 to 1 fixes it.

Not sure if this is a bug or as desired?

2018-01-21T18:42:22  [139737314608960] INFO  Manager __init__: config_file=config/zones.yaml
2018-01-21T18:42:22  [139737314608960] INFO  Manager __init__:   max_workers=1
2018-01-21T18:42:22  [139737314608960] INFO  Manager __init__:   max_workers=False
2018-01-21T18:42:22  [139737314608960] INFO  Manager dump: zone=bcruik.com., sources=()
Traceback (most recent call last):
  File "/usr/bin/octodns-dump", line 9, in <module>
    load_entry_point('octodns==0.8.8', 'console_scripts', 'octodns-dump')()
  File "/usr/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 362, in dump
    source.populate(zone, lenient=lenient)
  File "/usr/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 187, in populate
    lenient=lenient)
  File "/usr/lib/python2.7/site-packages/octodns/record.py", line 102, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record bcruik.com.
  - missing preference

**Comment by ross** [comment]
https://github.com/github/octodns/pull/173 should address this.
