### ISSUE TITLE
Can't resolve "Invalid record domain.tld., missing type"

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#184]
Hello,

i have no clue on why i get this error. I've checked like 10 times if i were missing anything... Can you help me? I also hope that having a complete zone file will help other people to run OctoDNS.
Thanks a lot, have a good day !

```
$ octodns-sync --config-file=./config/config.yaml
2018-02-02T01:21:57  [140525256952616] INFO  Manager __init__: config_file=./config/config.yaml
2018-02-02T01:21:57  [140525256952616] INFO  Manager __init__:   max_workers=1
2018-02-02T01:21:57  [140525256952616] INFO  Manager __init__:   max_workers=False
2018-02-02T01:21:57  [140525256952616] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False
2018-02-02T01:21:57  [140525256952616] INFO  Manager sync:   zone=r0x.fr.
2018-02-02T01:21:57  [140525256952616] INFO  Manager sync:   sources=['config'] -> targets=['cloudflare']
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 260, in sync
    plans = [p for f in futures for p in f.result()]
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 183, in _populate_and_plan
    source.populate(zone)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/yaml.py", line 69, in populate
    lenient=lenient)
  File "/usr/local/lib/python2.7/site-packages/octodns/record.py", line 78, in new
    raise Exception('Invalid record {}, missing type'.format(fqdn))
Exception: Invalid record r0x.fr., missing type
ERROR: Job failed: exit code 1
```

Zone file is here: https://hastebin.com/oyubozicax.hs

**Comment by yzguy** [comment]
Your Apex record is invalid:

```
'':
  - ttl: 300
  - type: A
    value: 5.135.102.21
  - type: MX
    values:
```

It should be like

```
'':
  - ttl: 300
    type: A
    value: 5.135.102.21
  - type: MX
    values:
```

If you have an array under a name, each is treated as a record. The `- ttl: 300` would be treated as one, and it has no `type` key, so it is invalid, hence the error.

**Comment by o-be-one** [comment]
Oh thanks a lot for your complete answer!
So i can remove TTL or add It for each entry. I think that the default TTL
is the one defined by the dns provider and i’ve read that you are thinking
about adding a default TTL in OctoDNS config, am i right ?
Le ven. 2 févr. 2018 à 00:00, Adam Smith <notifications@github.com> a
écrit :

**Comment by ross** [comment]
> So i can remove TTL or add It for each entry.

Yeah. If you remove it the error will be addressed. The records will be using the default value unless you add a specific override to them.

**Comment by o-be-one** [comment]
Thanks a lot again yzguy and ross :). Have an excellent weekend !
I close my issue.
