### ISSUE TITLE
SRV issue with OVH provider

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#189]
Hello,

Well i'm back with a SRV issue ... octodns validation was ok but doit did an error from OVH side.

Here my setting:
```
_srv._tcp:
  ttl: 300
  type: SRV
  value:
    port: 1234
    priority: 1
    target: mysrv.mydomain.tld.
    weight: 1

```

and here the octodns output:
```
********************************************************************************
* ovh (OvhProvider)
*   Create <SrvRecord SRV 300, _srv._tcp.mydomain.tld., [''1 1 1234 mysrv.mydomain.tld.'']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=36
* digitalocean (DigitalOceanProvider)
*   Create <SrvRecord SRV 300, _srv._tcp.mydomain.tld., [''1 1 1234 mysrv.mydomain.tld.'']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=36
********************************************************************************


2018-02-06T15:35:22  [139966085606184] INFO  OvhProvider[ovh] apply: making changes
2018-02-06T15:35:22  [139966085606184] INFO  OvhProvider[ovh] _apply: zone=mydomain.tld., len(changes)=1
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.8.8', 'console_scripts', 'octodns-sync')()
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 311, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/base.py", line 86, in apply
    self._apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 90, in _apply
    change)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 99, in _apply_create
    self.create_record(zone_name, params)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 391, in create_record
    **params)
  File "/usr/local/lib/python2.7/site-packages/ovh/client.py", line 376, in post
    return self.call('POST', _target, kwargs, _need_auth)
  File "/usr/local/lib/python2.7/site-packages/ovh/client.py", line 445, in call
    response=result)
ovh.exceptions.BadParametersError: Invalid domain name: 1 1 1234 mysrv.mydomain.tld 
OVH-Query-ID: FR.ws-1.5a79cb3a.3573.7811
ERROR: Job failed: exit code 1
```

I also see that i've one DNS updated after the failing doit ... So, do you have a way to prevent any change when a record issue from provider side appears? It's not critical i think cause we will remove it with editing the config to push but just wanted to notify your about this if you were not aware.

Thank you, have a good day :) !

**Comment by o-be-one** [comment]
Hello @ross , i'll be happy to provide a ovh api access to handle a domain i have on it but don't use for now, so you'll be able to test the bug.
In the meantime i think i'll just disable OVH DNS for my domain that needs a SRV.

**Comment by trnsnt** [comment]
@ross, @o-be-one will look at it asap this week. Keep you informed

**Comment by trnsnt** [comment]
@o-be-one I have made a Pull Request => https://github.com/github/octodns/pull/192
Hope it will be fine !

Have a nice end of day !

**Comment by o-be-one** [comment]
Thanks @trnsnt (from an old OVH sysadmin at PCI Montreal ;)).

**Comment by o-be-one** [comment]
Just tried your merged PR, worked like a charm. Thanks ross and trnsnt!
