### ISSUE TITLE
Single domain that is both public and private in Route53

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#190]
I have been poking at this off and on for a few months, and I wasn't sure if it was an octoDNS issue or a me issue.

We have a single domain set as two hosted zones in Route53, one public and one private. When attempting an `octodns-dump` against the domain, octoDNS is throwing an error about an empty geo value. There are no geo records set for either hosted zone.

config:
```
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:
  sillydomain.com.:
    sources:
      - route53
    targets:
      - config
```

octodns-dump debug output:
```
2018-02-06T09:50:14  [140736519537600] INFO  Manager __init__: config_file=config/ro_config_route53.yaml
2018-02-06T09:50:14  [140736519537600] INFO  Manager __init__:   max_workers=1
2018-02-06T09:50:14  [140736519537600] INFO  Manager __init__:   max_workers=False
2018-02-06T09:50:14  [140736519537600] DEBUG Manager __init__:   configuring providers
2018-02-06T09:50:14  [140736519537600] DEBUG YamlProvider[config] __init__: id=config, directory=./data, default_ttl=3600, enforce_order=1
2018-02-06T09:50:14  [140736519537600] DEBUG YamlProvider[config] __init__: id=config, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T09:50:14  [140736519537600] DEBUG Route53Provider[route53] __init__: id=route53, access_key_id=KEY, secret_access_key=***
2018-02-06T09:50:14  [140736519537600] DEBUG Route53Provider[route53] __init__: id=route53, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T09:50:14  [140736519537600] INFO  Manager dump: zone=sillydomain.com., sources=()
2018-02-06T09:50:14  [140736519537600] DEBUG YamlProvider[dump] __init__: id=dump, directory=data/, default_ttl=3600, enforce_order=1
2018-02-06T09:50:14  [140736519537600] DEBUG YamlProvider[dump] __init__: id=dump, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T09:50:14  [140736519537600] DEBUG Manager configured_sub_zones: subs=[]
2018-02-06T09:50:14  [140736519537600] DEBUG Zone __init__: zone=Zone<sillydomain.com.>, sub_zones=set([])
2018-02-06T09:50:14  [140736519537600] DEBUG Route53Provider[route53] populate: name=sillydomain.com., target=False, lenient=False
2018-02-06T09:50:14  [140736519537600] DEBUG Route53Provider[route53] _get_zone_id: name=sillydomain.com.
2018-02-06T09:50:14  [140736519537600] DEBUG Route53Provider[route53] r53_zones: loading
2018-02-06T09:50:15  [140736519537600] DEBUG Route53Provider[route53] _get_zone_id:   id=/hostedzone/PRIVATEID
2018-02-06T09:50:15  [140736519537600] DEBUG Route53Provider[route53] _load_records: zone_id=/hostedzone/PRIVATEID loading
Traceback (most recent call last):
  File "~/tmp/nosync/dns/env/bin/octodns-dump", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-dump')()
  File "~/tmp/nosync/dns/env/src/octodns/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/manager.py", line 360, in dump
    source.populate(zone, lenient=lenient)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/provider/route53.py", line 464, in populate
    data = getattr(self, '_data_for_{}'.format(record_type))(rrset)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/provider/route53.py", line 314, in _data_for_geo
    'values': [v['Value'] for v in rrset['ResourceRecords']],
KeyError: u'ResourceRecords'
```

Please let me know if this is a PEBCAK. 😄

**Comment by yzguy** [comment]
the `_data_for_geo` method is used for both A and AAAA records. https://github.com/github/octodns/blob/master/octodns/provider/route53.py#L322-L323

So it's not Geo Related, rather probably an A or AAAA record.
There should be a response from AWS that looks similar to

```
 'ResourceRecordSets': [{
    'Name': 'simple.unit.tests.',
    'Type': 'A',
    'ResourceRecords': [{
        'Value': '1.2.3.4',
    }, {
        'Value': '2.2.3.4',
    }],
    'TTL': 60,
}
```
I don't think they would let you make a record with no value, and I would assume there would also be a `ResourceRecords` key either way.

I'm betting this is related to both zones showing up in the `list-hosted-zones` output, but we aren't distinguishing if it's the private hosted one or the public hosted zone. If it's not, then I forsee a bug anyway because of it.

If you go into `~/tmp/nosync/dns/env/src/octodns/octodns/provider/route53.py` and add:

```
def _data_for_geo(self, rrset):
    print(rrset)
```

starting on line 311, then run it again. It should print out what the rrset looks like. Sanitize the output to remove identifying things, then if you could paste it here.

**Comment by brianeclow** [comment]
After seeing the record, I think is related to issue #26 

Re-ran the `octodns-dump` command with the added print:
```
2018-02-06T13:02:48  [140736519537600] INFO  Manager __init__: config_file=config/ro_config_route53.yaml
2018-02-06T13:02:48  [140736519537600] INFO  Manager __init__:   max_workers=1
2018-02-06T13:02:48  [140736519537600] INFO  Manager __init__:   max_workers=False
2018-02-06T13:02:48  [140736519537600] DEBUG Manager __init__:   configuring providers
2018-02-06T13:02:48  [140736519537600] DEBUG YamlProvider[config] __init__: id=config, directory=./data, default_ttl=3600, enforce_order=1
2018-02-06T13:02:48  [140736519537600] DEBUG YamlProvider[config] __init__: id=config, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] __init__: id=route53, access_key_id=KEY, secret_access_key=***
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] __init__: id=route53, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T13:02:48  [140736519537600] INFO  Manager dump: zone=sillydomain.com., sources=()
2018-02-06T13:02:48  [140736519537600] DEBUG YamlProvider[dump] __init__: id=dump, directory=data/, default_ttl=3600, enforce_order=1
2018-02-06T13:02:48  [140736519537600] DEBUG YamlProvider[dump] __init__: id=dump, apply_disabled=False, update_pcent_threshold=0, delete_pcent_threshold=0
2018-02-06T13:02:48  [140736519537600] DEBUG Manager configured_sub_zones: subs=[]
2018-02-06T13:02:48  [140736519537600] DEBUG Zone __init__: zone=Zone<sillydomain.com.>, sub_zones=set([])
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] populate: name=sillydomain.com., target=False, lenient=False
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] _get_zone_id: name=sillydomain.com.
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] r53_zones: loading
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] _get_zone_id:   id=/hostedzone/PRIVATEID
2018-02-06T13:02:48  [140736519537600] DEBUG Route53Provider[route53] _load_records: zone_id=/hostedzone/PRIVATEID loading
{u'AliasTarget': {u'HostedZoneId': 'ALIASEDHOSTEDID', u'EvaluateTargetHealth': True, u'DNSName': 'internal-000000000.region.elb.amazonaws.com.'}, u'Type': 'A', u'Name': 'app.sillydomain.com.'}
Traceback (most recent call last):
  File "~/tmp/nosync/dns/env/bin/octodns-dump", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-dump')()
  File "~/tmp/nosync/dns/env/src/octodns/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/manager.py", line 360, in dump
    source.populate(zone, lenient=lenient)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/provider/route53.py", line 465, in populate
    data = getattr(self, '_data_for_{}'.format(record_type))(rrset)
  File "~/tmp/nosync/dns/env/src/octodns/octodns/provider/route53.py", line 315, in _data_for_geo
    'values': [v['Value'] for v in rrset['ResourceRecords']],
KeyError: u'ResourceRecords'
```

**Comment by yzguy** [comment]
Yep, that looks just like #27.
