### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by ad-m** [github/octodns#201]
```
$ pip install -U https://github.com/github/octodns/archive/master.zip
Collecting https://github.com/github/octodns/archive/master.zip
  Downloading https://github.com/github/octodns/archive/master.zip
     \ 552kB 749kB/s
Requirement already up-to-date: PyYaml>=3.12 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: dnspython>=1.15.0 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: futures>=3.1.1 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: incf.countryutils>=1.0 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: ipaddress>=1.0.18 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: natsort>=5.0.3 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: python-dateutil>=2.6.1 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: requests>=2.13.0 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from octodns==0.8.8)
Requirement already up-to-date: setuptools in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from incf.countryutils>=1.0->octodns==0.8.8)
Requirement already up-to-date: six>=1.5 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from python-dateutil>=2.6.1->octodns==0.8.8)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from requests>=2.13.0->octodns==0.8.8)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from requests>=2.13.0->octodns==0.8.8)
Requirement already up-to-date: idna<2.7,>=2.5 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from requests>=2.13.0->octodns==0.8.8)
Requirement already up-to-date: certifi>=2017.4.17 in /tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages (from requests>=2.13.0->octodns==0.8.8)
Installing collected packages: octodns
  Found existing installation: octodns 0.8.8
    Uninstalling octodns-0.8.8:
      Successfully uninstalled octodns-0.8.8
  Running setup.py install for octodns ... done
Successfully installed octodns-0.8.8
(tmp.ENmvQeKxbo) ✔ ~/Devel/infra [octodns|✔] 
18:53 $ octodns-sync
Traceback (most recent call last):
  File "/tmp/tmp.ENmvQeKxbo/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.8.8', 'console_scripts', 'octodns-sync')()
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/octodns/cmds/sync.py", line 10, in <module>
    from octodns.manager import Manager
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/octodns/manager.py", line 13, in <module>
    from .provider.base import BaseProvider
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/octodns/provider/base.py", line 10, in <module>
    from .plan import Plan
  File "/tmp/tmp.ENmvQeKxbo/lib/python3.6/site-packages/octodns/provider/plan.py", line 8, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
$ python --version
Python 3.6.2
```

**Comment by ross** [comment]
Known shortcoming and something I want to get before we go to 1.0.

**Comment by nikaro** [comment]
Another blocker, OctoDNS uses `incf.countryutils` for which the pip package is not Python3 compatible cf. https://github.com/wyldebeast-wunderliebe/incf.countryutils/issues/2

**Comment by tnir** [comment]
@nikaro Yes, setup.py is not effective any more (cf. #265)...

**Comment by nikaro** [comment]
Found something else, some portions of code make use of the deprecated exception `message` attribute.

At least this:

```
diff --git a/octodns/provider/azuredns.py b/octodns/provider/azuredns.py
index 6eff4d7..d5d0982 100644
--- a/octodns/provider/azuredns.py
+++ b/octodns/provider/azuredns.py
@@ -296,7 +296,7 @@ class AzureProvider(BaseProvider):
             msg = 'The Resource \'Microsoft.Network/dnszones/{}\''.format(name)
             msg += ' under resource group \'{}\''.format(self._resource_group)
             msg += ' was not found.'
-            if msg == err.message:
+            if msg == err.args[0]:
                 # Then the only error is that the zone doesn't currently exist
                 if create:
                     self.log.debug('_check_zone:no matching zone; creating %s',
diff --git a/octodns/provider/dyn.py b/octodns/provider/dyn.py
index f47f77b..5d89fd0 100644
--- a/octodns/provider/dyn.py
+++ b/octodns/provider/dyn.py
@@ -397,7 +397,7 @@ class DynProvider(BaseProvider):
                     fqdn, _type = td.label.split(':', 1)
                 except ValueError as e:
                     self.log.warn("Failed to load TrafficDirector '%s': %s",
-                                  td.label, e.message)
+                                  td.label, e.args[0])
                     continue
                 tds[fqdn][_type] = td
             self._traffic_directors = dict(tds)
diff --git a/octodns/provider/ns1.py b/octodns/provider/ns1.py
index c432483..0806eef 100644
--- a/octodns/provider/ns1.py
+++ b/octodns/provider/ns1.py
@@ -202,7 +202,7 @@ class Ns1Provider(BaseProvider):
             geo_records = nsone_zone.search(has_geo=True)
             exists = True
         except ResourceException as e:
-            if e.message != self.ZONE_NOT_FOUND_MESSAGE:
+            if e.args[0] != self.ZONE_NOT_FOUND_MESSAGE:
                 raise
             records = []
             geo_records = []
@@ -356,7 +356,7 @@ class Ns1Provider(BaseProvider):
         try:
             nsone_zone = self._client.loadZone(domain_name)
         except ResourceException as e:
-            if e.message != self.ZONE_NOT_FOUND_MESSAGE:
+            if e.args[0] != self.ZONE_NOT_FOUND_MESSAGE:
                 raise
             self.log.debug('_apply:   no matching zone, creating')
             nsone_zone = self._client.createZone(domain_name)
diff --git a/octodns/provider/ovh.py b/octodns/provider/ovh.py
index d968da4..06b5ed9 100644
--- a/octodns/provider/ovh.py
+++ b/octodns/provider/ovh.py
@@ -64,7 +64,7 @@ class OvhProvider(BaseProvider):
             records = self.get_records(zone_name=zone_name)
             exists = True
         except ResourceNotFoundError as e:
-            if e.message != self.ZONE_NOT_FOUND_MESSAGE:
+            if e.args[0] != self.ZONE_NOT_FOUND_MESSAGE:
                 raise
             exists = False
             records = []
```

**Comment by danielgriggs** [comment]
Is there still development towards this?

**Comment by ross** [comment]
> Is there still development towards this?

Yeah. Just have been busy enough that I haven't had time to put towards it recently. Hopefully soon.

**Comment by ross** [comment]
https://github.com/github/octodns/pull/384 added py3 support

**Comment by danielgriggs** [comment]
Great!! thank you!

**Comment by max-wittig** [comment]
Can we have a new release with modern python support?

**Comment by ross** [comment]
https://github.com/github/octodns/pull/417
