### ISSUE TITLE
AzureDNS Provider Issue

### ISSUE THREAD

**Issue by chriskacerguis** [github/octodns#217]
Seeing this error when trying to use with the AzureDNS provider.  Would anyone happen to have a clue as to what the issue might be?  As far as I can tell, all my info for Azure is correct.

```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 37, in main
    manager = Manager(args.config_file)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 116, in __init__
    self.providers[provider_name] = _class(provider_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/azuredns.py", line 252, in __init__
    client_id, secret=key, tenant=directory_id
  File "/usr/local/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 440, in __init__
    self.set_token()
  File "/usr/local/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 473, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/local/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , MissingTokenError: (missing_token) Missing access token parameter.
ERROR: Job failed: exit code 1
```

**Comment by AaronHeady** [comment]
I work with Mohit. We'll take a look at this.

Aaron

**Comment by mohitsuley** [comment]
ACK. 
Checked to make sure the API wasn't acting up or anything - looks good. 
While I look deeper, can you try running a test from az command-set directly to make sure general command-line access is working for you? 

`az network dns zone list [--resource-group]`

**Comment by ross** [comment]
@omarkilani any specific thoughts on whether https://github.com/github/octodns/pull/331 fixes this? 

@chriskacerguis you mind giving it a test to see?

**Comment by omarkilani** [comment]
@ross nope... just figured they might have fixed some bug or something. A lot of code churn...
