### ISSUE TITLE
"KeyError: u'providers'" error

### ISSUE THREAD

**Issue by chriskacerguis** [github/octodns#218]
Hi All,

Seeing this error (not really sure what to make of it)

```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/octodns/cmds/sync.py", line 37, in main
    manager = Manager(args.config_file)
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 90, in __init__
    for provider_name, provider_config in self.config['providers'].items():
KeyError: u'providers'
```

Here is my production.yaml file, I'm not sure if there is something that I missed.

```yaml
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./domains
  azuredns:
    class: octodns.provider.azuredns.AzureProvider
    client_id: env/AZURE_CLIENT_ID
    key: env/AZURE_KEY
    directory_id: env/AZURE_DIRECTORY_ID
    sub_id: env/AZURE_SUBSCRIPTION_ID
    resource_group: 'my_resource_group '

zones:
  mydomain.net.:
    sources:
      - config
    targets:
      - azuredns
```
Any ideas or help would be greatly appreciated.

Thanks!

**Comment by chriskacerguis** [comment]
Going to close this.  PEBKAC error (I had mistyped the config file name on the command line)
