### ISSUE TITLE
CNAME cannot coexist with other records

### ISSUE THREAD

**Issue by heretogo** [github/octodns#242]
Can somebody help me debug the below error?
I believe it is complaining because there is an MX record as well as a CNAME on `subdomain.example.com`

```
Traceback (most recent call last):
  File "/home/.python_local/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/home/.python_local/local/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/home/.python_local/local/lib/python2.7/site-packages/octodns/manager.py", line 360, in dump
    source.populate(zone, lenient=lenient)
  File "/home/.python_local/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 256, in populate
    zone.add_record(record)
  File "/home/.python_local/local/lib/python2.7/site-packages/octodns/zone.py", line 91, in add_record
    .format(record.fqdn))
octodns.zone.InvalidNodeException: Invalid state, CNAME at subdomain.example.com. cannot coexist with other records
```

**Comment by ross** [comment]
That is the case. It's not valid RFC-wise for CNAMEs to coexist with other records on the same node.
