### ISSUE TITLE
Cloudflare KeyError: u'priority'

### ISSUE THREAD

**Issue by ericwingate** [github/octodns#248]
Looks like the cloudflare provider is throwing the following error.. Wondering if cloudflare made any changes to MX priority:

Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 289, in sync
    plans = [p for f in futures for p in f.result()]
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 225, in _populate_and_plan
    plan = target.plan(zone)
  File "/Library/Python/2.7/site-packages/octodns/provider/base.py", line 49, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 246, in populate
    lenient)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 223, in _record_for
    data = data_for(_type, records)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 160, in _data_for_MX
    'preference': r['priority'],
KeyError: u'priority'

**Comment by yzguy** [comment]
Just tried it for mine, no issues.

Do you mind doing editing `/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py` and adding a `print(records)` above line 158

The _data_for_MX method will then look like this

```
    def _data_for_MX(self, _type, records):
        values = []
        print(r)
        for r in records:
            values.append({
                'preference': r['priority'],
                'exchange': '{}.'.format(r['content']),
            })
        return {
            'ttl': records[0]['ttl'],
            'type': _type,
            'values': values,
        }
```

I'm curious what you're getting back from the API for the record that is throwing the exception.  Please sanitize the output of domains, etc.

**Comment by ross** [comment]
> Yeah, nevermind.. the MX record was jacked up in cloudflare. Closing this out.

If you remember would you mind dropping in how it was messed up. Sounds like someone else might be running into the same thing over in https://github.com/github/octodns/issues/250.

**Comment by ericwingate** [comment]
Yeah, I was able to correct it actually by modifying the priority for MX records in cloudflare. I had ‘0’ priority set, and changed it to ‘1’ within cloudflare. After the change I was able to use octodns without any issues.  It was almost like cloudflare didn’t allow 0 priority any longer. So changing to ‘1’ manually within cloudflare worked for me.
