### ISSUE TITLE
MX records in cloudflare

### ISSUE THREAD

**Issue by alexverilhac** [github/octodns#250]
Hi everyone !
I'm using octodns since few month and I really appreciate it.
But today when I try to sync with cloudflare, I got this error : 
```
Traceback (most recent call last):
  File "/home/alex/dns/env/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 289, in sync
    plans = [p for f in futures for p in f.result()]
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 225, in _populate_and_plan
    plan = target.plan(zone)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/provider/base.py", line 49, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 246, in populate
    lenient)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 223, in _record_for
    data = data_for(_type, records)
  File "/home/alex/dns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 160, in _data_for_MX
    'preference': r['priority'],
KeyError: u'priority'
```

Can you help me, I thought the problem was the priority set to 0 but even if I set it to 1 or 10 I have this error.

My config : 
```
---
'':
  - ttl: 3600
    type: A
    value: 151.80.195.206
  - ttl: 3600
    type: MX
    values:
      - priority: 0
        value: residencesainteanne-fr.mail.protection.outlook.com.
  - ttl: 3600
    type: TXT
    values:
      - v=spf1 a mx include:_spf.point-web.fr ~all
      - v=spf1 include:spf.protection.outlook.com -all
      - MS=ms49229553
_sip._tls:
  ttl: 3600
  type: SRV
  values:
    - port: 443
      priority: 100
      target: sipdir.online.lync.com.
      weight: 1
_sipfederationtls._tcp:
  ttl: 3600
  type: SRV
  values:
    - port: 5061
      priority: 100
      target: sipfed.online.lync.com.
      weight: 1
autodiscover:
  ttl: 3600
  type: CNAME
  value: autodiscover.outlook.com.
enterpriseenrollment:
  ttl: 3600
  type: CNAME
  value: enterpriseenrollment.manage.microsoft.com.
enterpriseregistration:
  ttl: 3600
  type: CNAME
  value: enterpriseregistration.windows.net.
ftp:
  ttl: 3600
  type: CNAME
  value: residencesainteanne.fr.
imap:
  ttl: 3600
  type: CNAME
  value: fo-mailpop-1.point-web.fr.
lyncdiscover:
  ttl: 3600
  type: CNAME
  value: webdir.online.lync.com.
mail:
  ttl: 3600
  type: CNAME
  value: vm-mail0.point-web.fr.
msoid:
  ttl: 3600
  type: CNAME
  value: clientconfig.microsoftonline-p.net.
'pointweb._domainkey':
  ttl: 3600
  type: CNAME
  value: dkim-customers.point-web.fr.
pop:
  ttl: 3600
  type: CNAME
  value: fo-mailsmtp-1.point-web.fr.
sip:
  ttl: 3600
  type: CNAME
  value: sipdir.online.lync.com.
smtp:
  ttl: 3600
  type: CNAME
  value: fo-mailsmtp-1.point-web.fr.
webmail:
  ttl: 3600
  type: CNAME
  value: fo-mailwebmail-1.point-web.fr.
www:
  ttl: 3600
  type: CNAME
  value: residencesainteanne.fr.
```

**Comment by ross** [comment]
There was a similar sounding report over in https://github.com/github/octodns/issues/248 yesterday. You might take a look at that to see if you're running into the same thing.

**Comment by yzguy** [comment]
@alexverilhac the `_data_for` methods are for converting responses from Cloudflare's API into OctoDNS's structure for records.

Definitely let us know if you figure out the issue, that way can look to see if we can add something into OctoDNS to handle these cases.

**Comment by ericwingate** [comment]
Yeah look at my comment in #248. I think cloudflare made a change. Try manually changing the MX priority within the cloudflare portal manually. Change it to anything other than 0, then use octodns to change it back to what you intend.
