### ISSUE TITLE
New package requirement for GoogleCloudProvider

### ISSUE THREAD

**Issue by tnir** [github/octodns#256]
We can use the google-cloud-dns package for GoogleCloudProdivder as The google-cloud Python package was completely deprecated on June 18, 2018.

Otherwise you will see the following error:
 ```bash
$ pip install octodns google-cloud
[snipped]
Installing collected packages: PyYaml, dnspython, futures, incf.countryutils, ipaddress, natsort, six, python-dateutil, idna, chardet, urllib3, certifi, requests, octodns, google-cloud
Successfully installed PyYaml-3.13 certifi-2018.8.13 chardet-3.0.4 dnspython-1.15.0 futures-3.2.0 google-cloud-0.34.0 idna-2.7 incf.countryutils-1.0 ipaddress-1.0.22 natsort-5.3.3 octodns-0.9.1 python-dateutil-2.6.1 requests-2.19.1 six-1.11.0 urllib3-1.23
$ octodns-dump --config-file=config/production.yaml --output-dir=tmp/ example.com. googlecloud
2018-08-16T01:53:46  [139980834925448] INFO  Manager __init__: config_file=config/production.yaml
2018-08-16T01:53:46  [139980834925448] INFO  Manager __init__:   max_workers=1
2018-08-16T01:53:46  [139980834925448] INFO  Manager __init__:   max_workers=False
2018-08-16T01:53:46  [139980834925448] ERROR Manager _get_{}_class: Unable to import module octodns.provider.googlecloud.GoogleCloudProvider
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 154, in _get_named_class
    module = import_module(module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/googlecloud.py", line 14, in <module>
    from google.cloud import dns
ImportError: No module named google.cloud
Traceback (most recent call last):
  File "/usr/local/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/dump.py", line 30, in main
    manager = Manager(args.config_file)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 98, in __init__
    _class = self._get_named_class('provider', _class)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 158, in _get_named_class
    raise Exception('Unknown {} class: {}'.format(_type, _class))
Exception: Unknown provider class: octodns.provider.googlecloud.GoogleCloudProvider
```

## References

> WARNING: The google-cloud Python package is deprecated. On June 18, 2018, this package will no longer install any other packages. Please install the product-specific google-cloud-* packages needed for your application.

https://pypi.org/project/google-cloud/0.34.0/

**Comment by ross** [comment]
> $ pip install octodns google-cloud

As a work-around you can force things to install an older working version, the known good version according to requirements.txt.

```
(env)otter:octodns ross$ pip install octodns google-cloud==0.32.0
...
(env)otter:octodns ross$ python
Python 2.7.14 (default, Mar 10 2018, 00:01:04)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import dns
>>>
```

I'm actually glad they've broken things up there was a ton of stuff getting installed that was of no real use. Will look at getting a PR going that updates the required package.

**Comment by tnir** [comment]
Thanks for showing the workaround I forgot to put into the issue. PR is #257.
