### ISSUE TITLE
Issue with 426 Client Error on Sync from Cloudflare

### ISSUE THREAD

**Issue by wingZero21** [github/octodns#261]
Hi,

I am seeing the below error when attempting to test sync from Cloudflare to Route53.

Can you advise what might be causing this to occur? Is this a failing in one of the modules that the provider is using?

Details:
```2018-08-29T15:29:30  [140736137941952] DEBUG urllib3.connectionpool https://api.cloudflare.com:443 "GET /client/v4/zones?page=1 HTTP/1.1" 426 304
2018-08-29T15:29:30  [140736137941952] DEBUG CloudflareProvider[cloudflare] _request:   status=426
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 294, in sync
    plans = [p for f in futures for p in f.result()]
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/octodns/manager.py", line 217, in _populate_and_plan
    source.populate(zone)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 233, in populate
    records = self.zone_records(zone)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 193, in zone_records
    zone_id = self.zones.get(zone.name, False)
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 93, in zones
    resp = self._request('GET', '/zones', params={'page': page})
  File "/Library/Python/2.7/site-packages/octodns/provider/cloudflare.py", line 84, in _request
    resp.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://api.cloudflare.com/client/v4/zones?page=1```

**Comment by yzguy** [comment]
Looks related to SSL: https://community.cloudflare.com/t/the-remote-server-returned-an-error-426-upgrade-required/20544

**Comment by wingZero21** [comment]
@yzguy I am currently using python 2.7.10

**Comment by wingZero21** [comment]
I tried re-running this on a 7.5 CentOS server and it does seem to be running without this error now currently. 

It must have been some dep on the local mac that was causing this to occur.

Cheers

**Comment by ross** [comment]
My guess would be that the version of python on the system having problems doesn't support TLS 1.2 and Cloudflare is enforcing it's use.
