### ISSUE TITLE
YAML should not require keys in a particular order

### ISSUE THREAD

**Issue by thockin** [github/octodns#267]
YAML is written and read by humans.  Forcing the keys to be alphabetical hurts readability.  I should be able to put "type" before "ttl".

```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 294, in sync
    plans = [p for f in futures for p in f.result()]
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 217, in _populate_and_plan
    source.populate(zone)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/yaml.py", line 60, in populate
    yaml_data = safe_load(fh, enforce_order=self.enforce_order)
  File "/usr/local/lib/python2.7/dist-packages/octodns/yaml.py", line 39, in safe_load
    return load(stream, SortEnforcingLoader if enforce_order else SafeLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 43, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python2.7/dist-packages/octodns/yaml.py", line 22, in _construct
    ret = self.construct_pairs(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 145, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python2.7/dist-packages/octodns/yaml.py", line 30, in _construct
    .format(expected, key, node.start_mark))
yaml.constructor.ConstructorError: keys out of order: expected ttl got type at   in "./config/kubernetes.io.yaml", line 25, column 3

**Comment by thockin** [comment]
Found the flag :)

**Comment by ross** [comment]
Heh. I've though about having an option to force the names to be in order, but ignore the keys. Mostly we have some large zones and it gets really annoying if the names in them aren't alphabetized :grin:

**Comment by johnlane** [comment]
@ross I just hit on this one myself. If this alpha-ordering requirement is by design then should the code report an error and exit rather than triggering an exception and carrying on?

The [docs](https://github.com/github/octodns#config) show the `enforce_order` setting but there is no explanation as to why enforcement would be preferable (I assume it's preferable, as it's the default).

**Comment by ross** [comment]
> code report an error and exit rather than triggering an exception and carrying on?

It is throwing an exception and stopping, but there are (probably) multiple threads working on different zones at the same time. It'll finish processing them and then emit the results and stop.

> The [docs](https://github.com/github/octodns#config) show the `enforce_order` setting but there is no explanation as to why enforcement would be preferable (I assume it's preferable, as it's the default).

Not sure what you're looking for. It's that way just as a best practice to keep things more organized as [stated above](https://github.com/github/octodns/issues/267#issuecomment-419279601).
