### ISSUE TITLE
route53 -> gce validation error

### ISSUE THREAD

**Issue by armin1402** [github/octodns#294]
Hey there,

im trying to mirror an zone from route53 to gce... mabye someone has an idea what's wrong here.

## Config
``` 
---
providers:
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY
    secret_access_key: env/AWS_SECRET_KEY
  googlecloud:
    class: octodns.provider.googlecloud.GoogleCloudProvider
    project: my-project
    credentials_file: ...my.path...

zones:

  MY_DOMAIN.de.:
    sources:
      - route53
    targets:
      - googlecloud
``` 
## Output
``` 
(env) user@machine:~/dns$ octodns-sync --config-file config/MY_DOMAIN.yaml --debug
2018-11-05T14:45:14  [140650944702272] INFO  Manager __init__: config_file=config/MY_DOMAIN.yaml
2018-11-05T14:45:14  [140650944702272] INFO  Manager __init__:   max_workers=1
2018-11-05T14:45:14  [140650944702272] INFO  Manager __init__:   max_workers=False
2018-11-05T14:45:14  [140650944702272] DEBUG Manager __init__:   configuring providers
2018-11-05T14:45:14  [140650944702272] DEBUG Route53Provider[route53] __init__: id=route53, access_key_id=***, secret_access_key=***
2018-11-05T14:45:14  [140650944702272] DEBUG Route53Provider[route53] __init__: id=route53, apply_disabled=False, update_pcent_threshold=0.30, delete_pcent_threshold=0.30
2018-11-05T14:45:14  [140650944702272] DEBUG GoogleCloudProvider[googlecloud] __init__: id=googlecloud, apply_disabled=False, update_pcent_threshold=0.30, delete_pcent_threshold=0.30
2018-11-05T14:45:14  [140650944702272] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False
2018-11-05T14:45:14  [140650944702272] INFO  Manager sync:   zone=MY_DOMAIN.de.
2018-11-05T14:45:14  [140650944702272] INFO  Manager sync:   sources=['route53'] -> targets=['googlecloud']
2018-11-05T14:45:14  [140650944702272] DEBUG Manager sync:   populating, zone=MY_DOMAIN.de.
2018-11-05T14:45:14  [140650944702272] DEBUG Manager configuuser_sub_zones: subs=[]
2018-11-05T14:45:14  [140650944702272] DEBUG Zone __init__: zone=Zone<MY_DOMAIN.de.>, sub_zones=set([])
2018-11-05T14:45:14  [140650944702272] DEBUG Route53Provider[route53] populate: name=MY_DOMAIN.de., target=False, lenient=False
2018-11-05T14:45:14  [140650944702272] DEBUG Route53Provider[route53] _get_zone_id: name=MY_DOMAIN.de.
2018-11-05T14:45:14  [140650944702272] DEBUG Route53Provider[route53] r53_zones: loading
2018-11-05T14:45:14  [140650944702272] DEBUG urllib3.util.retry Converted retries value: False -> Retry(total=False, connect=None, read=None, userirect=0, status=None)
2018-11-05T14:45:14  [140650944702272] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): route53.amazonaws.com:443
2018-11-05T14:45:15  [140650944702272] DEBUG urllib3.connectionpool https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone HTTP/1.1" 200 1395
2018-11-05T14:45:15  [140650944702272] DEBUG Route53Provider[route53] _get_zone_id:   id=/hostedzone/ZONE_ID
2018-11-05T14:45:15  [140650944702272] DEBUG Route53Provider[route53] _load_records: zone_id=/hostedzone/ZONE_ID loading
2018-11-05T14:45:15  [140650944702272] DEBUG urllib3.util.retry Converted retries value: False -> Retry(total=False, connect=None, read=None, userirect=0, status=None)
2018-11-05T14:45:15  [140650944702272] DEBUG urllib3.connectionpool https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone/ZONE_ID/rrset HTTP/1.1" 200 8999
2018-11-05T14:45:15  [140650944702272] DEBUG Record __init__: zone.name=MY_DOMAIN.de., type=    ARecord, name=
2018-11-05T14:45:15  [140650944702272] DEBUG Record __init__: zone.name=MY_DOMAIN.de., type=   NsRecord, name=
Traceback (most recent call last):
  File "/home/user/dns/env/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 294, in sync
    plans = [p for f in futures for p in f.result()]
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 217, in _populate_and_plan
    source.populate(zone)
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 499, in populate
    lenient=lenient)
  File "/home/user/dns/env/local/lib/python2.7/site-packages/octodns/record.py", line 106, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record MY_DOMAIN.de.
  - missing trailing .
  - missing trailing .
  - missing trailing .
  - missing trailing .
``` 

I'm using version 0.9.3

**Comment by armin1402** [comment]
Oh, found it... 

There was an mx record without trailing . in the value input field. After fixing the missing . everything works.
