### ISSUE TITLE
OVH: deleted entry and got ResourceNotFoundError

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#318]
Hello OctoDNS,

i've deleted 2 entries in my config file and OVH is now broke. Here few informations.
I use Gitlab CI to automatize my OctoDNS system, it works perfectly since almost 1y. 3 providers are set for this domaine.

**Error:**
```
2019-02-04T15:54:39  [140029662120840] INFO  OvhProvider[ovh] plan: desired=DOMAIN.TLD.
2019-02-04T15:54:39  [140029662120840] INFO  ovh.vendor.requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): eu.api.ovh.com
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 301, in sync
    plans = [p for f in futures for p in f.result()]
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 237, in _populate_and_plan
    plan = target.plan(zone)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/base.py", line 49, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 64, in populate
    records = self.get_records(zone_name=zone_name)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 358, in get_records
    return [self.get_record(zone_name, record_id) for record_id in records]
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 368, in get_record
    '/domain/zone/{}/record/{}'.format(zone_name, record_id))
  File "/usr/local/lib/python2.7/site-packages/ovh/client.py", line 347, in get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/site-packages/ovh/client.py", line 443, in call
    response=result)
ovh.exceptions.ResourceNotFoundError: The requested object (id = 15874XXX) does not exist 
OVH-Query-ID: EU.ext-2.5XXXXX46.29713.d55dXXX1-881e-4e81-XXXX-8416XXXX4879
```

**Config:**
```
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
  ovh:
    class: octodns.provider.ovh.OvhProvider
    endpoint: ovh-eu
    application_key: env/OVH_APP_KEY
    application_secret: env/OVH_APP_SECRET
    consumer_key: env/OVH_CONSUMER_KEY
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: env/CF_MAIL
    token: env/CF_TOKEN
  digitalocean:
    class: octodns.provider.digitalocean.DigitalOceanProvider
    token: env/DO_TOKEN

zones:
  DOMAIN.TLD.:
    sources:
      - config
    targets:
      - cloudflare
      - ovh
      - digitalocean
```

**CI Pipeline:**
```
image: python:2-alpine

stages:
  - test
  - deploy

before_script:
  - python --version
  - pip --version
  - pip install ovh
  - apk add --update git
  - pip install git+https://github.com/github/octodns.git

Check config:
  stage: test
  script: "octodns-sync --config-file=./config/config.yaml"
  allow_failure: false
    
Update DNS:
  stage: deploy
  script: "octodns-sync --config-file=./config/config.yaml --doit"
  when: on_success
  only:
    - master
```

We removed 2 DNS entries from the domain config file and got this error, that's all.

Thanks for your support!

**Comment by o-be-one** [comment]
Still stuck, any support? Thanks

**Comment by ross** [comment]
Sorry I don't have access to OVH and I'm not really familiar with it. 

/cc @trnsnt who wrote the provider originally.

**Comment by rdemendoza** [comment]
+1
