### ISSUE TITLE
CloudFlare SRV : too many values to unpack

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#324]
Hello folks,

i've added 2 SRV in my zone config and CloudFlare seems to be not able to "unpack" them. The same config is provided to DigitalOcean and no issue with it.

We use the latest OctoDNS from master branch, with Python 2.7 on Alpine Linux.

```
_minecraft._tcp.hoodoo:
  ttl: 14400
  type: SRV
  value:
    port: 44354
    priority: 0
    target: sub.otherdomain.tld.
    weight: 5
_minecraft._tcp.nail:
  ttl: 14400
  type: SRV
  value:
    port: 44264
    priority: 0
    target: sub.otherdomain.tld.
    weight: 5
```

```
2019-02-28T16:39:52  [140078134123368] INFO  CloudflareProvider[cloudflare] apply: making changes
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/base.py", line 93, in apply
    self._apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 558, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 414, in _apply_Create
    for content in self._gen_data(new):
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 373, in _gen_data
    for content in contents_for(record):
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 343, in _contents_for_SRV
    service, proto = record.name.split('.', 2)
ValueError: too many values to unpack
````

Thanks, let me know if you need more informations :).

**Comment by yzguy** [comment]
Simple replication:

```
>>> name = '_minecraft._tcp'
>>> service, proto = name.split('.', 2)

>>> name = '_minecraft._tcp.hoodoo'
>>> service, proto = name.split('.', 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

The provider seems to assume that you'd only do SRV records under the domain, rather than under a sub-domain.

**Comment by o-be-one** [comment]
Yes it seems to be the issue. Also, Cloudflare support subdomain so it's probably more an issue on the cli side.
http://prntscr.com/mrgwyl

**Comment by yzguy** [comment]
Thinking maybe something like this logic

```
>>> name = '_minecraft._tcp.hoodoo.boodoo.voodoo'
>>> splitname = name.split('.')
>>> service, proto, domain = splitname[0], splitname[1], ".".join(splitname[2:])
>>> service
'_minecraft'
>>> proto
'_tcp'
>>> domain
'hoodoo.boodoo.voodoo'
```

**Comment by o-be-one** [comment]
Thanks @yzguy for your support and fix :).
This answer and merge request fixed my issue.
Have a good week!
