### ISSUE TITLE
NS1 - Geo Region - invalid answer metadata: "" is not a valid "country"

### ISSUE THREAD

**Issue by warmfusion** [github/octodns#335]
Version: octoDNS 0.9.4

Using the example provided in records.md, when trying to load a `yaml` file to ns1 for a domain the following error is thrown;

```
********************************************************************************
* tobyjackson.net.
********************************************************************************
* nsone (Ns1Provider)
*   Create <ARecord A 300, test.tobyjackson.net., ['111.111.111.5'], {'EU': 'Geo EU None None ['111.111.111.4']', 'NA-US-NY': 'Geo NA US NY ['111.111.111.1']', 'OC-AU': 'Geo OC AU None ['111.111.111.3']', 'NA-US-CA': 'Geo NA US CA ['111.111.111.2']'}> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=2
********************************************************************************


2019-04-02T17:03:26  [140238595214184] INFO  Ns1Provider[nsone] apply: making changes
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/base.py", line 93, in apply
    self._apply(plan)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ns1.py", line 367, in _apply
    change)
  File "/usr/local/lib/python2.7/site-packages/octodns/provider/ns1.py", line 311, in _apply_Create
    meth(name, **params)
  File "/usr/local/lib/python2.7/site-packages/ns1/zones.py", line 140, in add_X
    return record.create(callback=callback, errback=errback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ns1/records.py", line 130, in create
    callback=success, errback=errback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ns1/rest/records.py", line 113, in create
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ns1/rest/records.py", line 124, in create_raw
    errback=errback)
  File "/usr/local/lib/python2.7/site-packages/ns1/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ns1/rest/transport/requests.py", line 60, in send
    resp.text)
ns1.rest.errors.ResourceException: server error: invalid answer metadata: "" is not a valid "country"
```

## yamls

``` yaml 
# tobyjackson.net.yaml
---
? ''
: type: ALIAS
  value: example.com

test:
  geo:
    NA-US-NY:
    - 111.111.111.1
    NA-US-CA:
    - 111.111.111.2
    OC-AU:
    - 111.111.111.3
    EU:
    - 111.111.111.4
  ttl: 300
  type: A
  value: 111.111.111.5
```

## production.yaml

``` yaml
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./octozones
    enforce_order: false
  nsone:
    class: octodns.provider.ns1.Ns1Provider
    api_key: env/NSONE_KEY
zones:
  tobyjackson.net.:
    sources:
      - config
    targets:
      - nsone

```

running a simply octodns-sync

**Comment by ross** [comment]
Hrm, I haven't had a chance to dig into the geo support in the NS1 provider. I believe they did most of it on the server side. I'm not seeing anything wrong with your example and I don't know offhand what would cause that. I'm pretty booked up at the moment so I'm not sure when I'll have a chance to look. At some point in the future I'd like to look at implementing the new `dynamic` record type for NS1, but tbh I have no clue when I'll get a stretch of time to do it. If no one beats me to it, that's probably when i'd be able to look into this.
