### ISSUE TITLE
Azure TXT Record too long

### ISSUE THREAD

**Issue by jonathanlavoie-optel** [github/octodns#361]
TXT record too long.

This record pass:
`v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohsnP896F0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo55`

This one not (one more digit at the end:
`v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohsnP896F0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo555`

I'm getting this error:
```
2019-05-09T17:00:13  [140592352986944] INFO  AzureProvider[azuredns] apply: making changes
2019-05-09T17:00:13  [140592352986944] INFO  adal-python 1bcb48cf-4df2-41d7-9eb8-5ffb500f29a8 - TokenRequest:Getting token with client credentials.
Traceback (most recent call last):
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in sync
    total_changes += target.apply(plan)
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/octodns/provider/base.py", line 93, in apply
    self._apply(plan)
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/octodns/provider/azuredns.py", line 498, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/octodns/provider/azuredns.py", line 465, in _apply_Create
    parameters=ar.params)
  File "/mnt/c/Projects/pub-dns-as-code/dns/env/local/lib/python2.7/site-packages/azure/mgmt/dns/v2018_05_01/operations/record_sets_operations.py", line 204, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/51016543-f21e-4dc0-a73c-f03eeb42d373/resourceGroups/pub-dns-as-code/providers/Microsoft.Network/dnsZones/testdns2.com/TXT/google._domainkey?api-version=2018-05-01
```

Here is my yaml file:
```
---
? ''
: - ttl: 86400
    type: A
    value: 1.2.3.4
  - ttl: 86400
    type: MX
    values:
    - exchange: aspmx.l.google.com.
      preference: 10
    - exchange: alt1.aspmx.l.google.com.
      preference: 20
    - exchange: alt2.aspmx.l.google.com.
      preference: 30
    - exchange: aspmx2.googlemail.com.
      preference: 40
    - exchange: aspmx3.googlemail.com.
      preference: 50
google._domainkey:
  ttl: 86400
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohsnP896F0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo555666
intranet:
  ttl: 86400
  type: A
  values:
  - 2.3.4.5
  - 3.4.5.6
  - 4.5.6.7
jira:
  ttl: 86400
  type: A
  value: 2.3.4.5
vcs:
  ttl: 86400
  type: A
  value: 6.6.6.7
www:
  ttl: 86400
  type: CNAME
  value: example.com.
www2:
  ttl: 86400
  type: CNAME
  value: example2.com.
yo:
  ttl: 86400
  type: A
  value: 1.1.2.2
yoyo:
  ttl: 86400
  type: A
  value: 1.1.4.5
```

**Comment by ross** [comment]
Interesting. Hadn't run into that problem before. Are you able to push that record to other providers without problem or haven't tried? 

Wonder if Azure just has a hard limit on the size or if it requires chunking the record. There are several providers that make use of a chunked value for large TXT (and similar) records https://github.com/github/octodns/search?q=chunked&unscoped_q=chunked. I don't have access to Azure DNS set up so I can't check or test myself.

**Comment by jonathanlavoie-optel** [comment]
I had the same issue with terraform with Azure.
I solved the issue by changing the provider .. now with Cloudflare.
Works like a charm.

**Comment by ppieprzycki** [comment]
@ross @h-hwang  Can you please help with this issue. 
I have the same behaviour and it seems that appears when the record line is too long 

eg sfp record.  The limitation seems to be 256 chars 
"value": ["v=spf1 ip4:10.10.0.0/24 ip4:10.10.1.0/24 ip4:10.10.2.0/24 ip4:10.10.3.0/24 ip4:10.10.4.0/24 ip4:10.10.5.0/24 ip4:10.10.6.0/24 ip4:10.10.7.0/24 ip4:10.10.8.0/24 ip4:10.10.9.0/24 ip4:10.10.10.0/24 ip4:10.10.11.0/24 ip4:10.10.12.0/24 ip4:10.10.13.0/24  ~all"]
				
We can go with a longer record if we use multiple elements in array eg. 
"value": ["v=spf1 ip4:10.10.0.0/24 ip4:10.10.1.0/24 ip4:10.10.2.0/24 ip4:10.10.3.0/24 ip4:10.10.4.0/24 ip4:10.10.5.0/24 ip4:10.10.6.0/24 ip4:10.10.7.0/24 ip4:10.10.8.0/24 ip4:10.10.9.0/24 ip4:10.10.10.0/24 ip4:10.10.11.0/24 ip4:10.10.12.0/24 ip4:10.10.13.0/24",
"ip4:10.10.14.0/24 ip4:10.10.15.0/24 ip4:10.10.16.0/24  ~all"]

Can you fix or advise how to implement in code. 
Regards
