### ISSUE TITLE
Route53 geo change fails

### ISSUE THREAD

**Issue by kluzas** [github/octodns#370]
Hello,

I have initial configuration of geo balancing with route53 and Dyn.
It looks like this:
```
...
cdn:
  dynamic:
    pools:
      direct:
        values: 
        - value: direct.test.dev.
    rules:
    - geos:
      - OC
      pool: direct
  octodns:
    healthcheck:
      host: direct.test.dev
      path: /haproxy_healthcheck
      port: 80
      protocol: HTTP
    route53:
      healthcheck:
        measure_latency: false
  ttl: 60
  type: CNAME
  value: test.dev.cdn.cloudflare.net.
...
```
This configuration is sucessfuly applied to both providers.
The issue is whenever I add additional geo zone for ex.:
```
...
    rules:
    - geos:
      - AS
      - OC
      pool: direct
...
```
And route53 api fails with this error:
```
Traceback (most recent call last):
  File "/--hidden--/octoDNS/venv/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in sync
    total_changes += target.apply(plan)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/base.py", line 93, in apply
    self._apply(plan)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 1346, in _apply
    self._really_apply(batch, zone_id)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 1357, in _really_apply
    HostedZoneId=zone_id, ChangeBatch=batch)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Tried to create an alias that targets _octodns-direct-pool.cdn.test.dev., type CNAME in zone Z3EN5KW2XGH8Q2, but that target was not found]
```

**Comment by ross** [comment]
Hi @kluzas I believe that problem may have been fixed by https://github.com/github/octodns/pull/366. That's currently in master, but doesn't appear to have been in any released versions yet.

**Comment by kluzas** [comment]
Hi @ross. I just came back from my vacation and found out that 0.9.6 is already released. I have checked that Route53 now accepts geo changes without error. So I am closing this one. But there are some new problems but now with Dyn provider. Will try to dig in and open a ticket if won't find an easy workaround.
```
2019-07-18T08:42:03  [139879879145280] INFO  DynProvider[dyn] apply: making changes
Traceback (most recent call last):
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in sync
    total_changes += target.apply(plan)
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/base.py", line 93, in apply
    self._apply(plan)
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/dyn.py", line 1397, in _apply
    changes = self._apply_traffic_directors(desired, changes, dyn_zone)
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/dyn.py", line 1366, in _apply_traffic_directors
    mod(dyn_zone, c)
  File "/home/k.cernauskis/dev/--hidden--/octoDNS/venv/local/lib/python2.7/site-packages/octodns/provider/dyn.py", line 1311, in _mod_dynamic_Update
    if change.existing.geo:
AttributeError: 'CnameRecord' object has no attribute 'geo'
```

**Comment by ross** [comment]
> ```
> AttributeError: 'CnameRecord' object has no attribute 'geo'
> ```

👍 I'd call the `CNAME` dynamic support beta mainly b/c I don't currently have any uses of it so it's much less thoroughly tested than `A` so it won't surprise me if there are problems that haven't been shaken out.
