### ISSUE TITLE
Multiple Apex Records per zone with Exclude/Include

### ISSUE THREAD

**Issue by Moumoutaru** [github/octodns#371]
Since some providers do not support ALIAS records on the apex, when zones are pushed to those providers, say Google Cloud DNS in my case, the Apex record is never created.

It would be nice to be able to do something like this:

```
---
? ''
: - octodns:
      cloudflare:
        proxied: true
      included:
        - cloudflare
    ttl: 1
    type: ALIAS
    value: xyz.mydomain.tld
: - octodns:
      included:
        - google_cloud
    ttl: 1
    type: A
    value: 1.2.3.4
```

Where the expected behavior would be that when running `octodns-sync --config-file=config.yml mydomain.tld.` cloudflare would receive one apex record and google cloud dns would receive the other. Is this possible right now somehow? I tried the above and I am seeing:

```
 ~/git/web-ops/octodns   develop ●  octodns-sync --config-file=config.yml mydomain.tld.
2019-07-03T12:11:35  [140465616254144] INFO  Manager __init__: config_file=config.yml
2019-07-03T12:11:35  [140465616254144] INFO  Manager __init__:   max_workers=1
2019-07-03T12:11:35  [140465616254144] INFO  Manager __init__:   max_workers=False
2019-07-03T12:11:35  [140465616254144] INFO  Manager sync: eligible_zones=['mydomain.tld.'], eligible_targets=[], dry_run=True, force=False
2019-07-03T12:11:35  [140465616254144] INFO  Manager sync:   zone=mydomain.tld
2019-07-03T12:11:35  [140465616254144] INFO  Manager sync:   sources=['config'] -> targets=['cloudflare', 'google_cloud']
Traceback (most recent call last):
  File "/usr/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.9.5', 'console_scripts', 'octodns-sync')()
  File "/usr/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 301, in sync
    plans = [p for f in futures for p in f.result()]
  File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 224, in _populate_and_plan
    source.populate(zone)
  File "/usr/lib/python2.7/site-packages/octodns/provider/yaml.py", line 77, in populate
    self._populate_from_file(filename, zone, lenient)
  File "/usr/lib/python2.7/site-packages/octodns/provider/yaml.py", line 52, in _populate_from_file
    yaml_data = safe_load(fh, enforce_order=self.enforce_order)
  File "/usr/lib/python2.7/site-packages/octodns/yaml.py", line 39, in safe_load
    return load(stream, SortEnforcingLoader if enforce_order else SafeLoader)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "./config/mydomain.tld.yaml", line 2, column 1
expected <block end>, but found ':'
  in "./config/mydomain.tld.yaml", line 11, column 1
```

**Comment by brianeclow** [comment]
I think if you remove the `:` from line 11, then it should work as expected.

**Comment by Moumoutaru** [comment]
@brianeclow That worked. Thanks!

```
---
? ''
: - octodns:
      cloudflare:
        proxied: true
      included:
        - cloudflare
    ttl: 1
    type: ALIAS
    value: xyz.mydomain.tld
  - octodns:
      included:
        - google_cloud
    ttl: 1
    type: A
    value: 1.2.3.4
```
