### ISSUE TITLE
Add support for 'LUA' records in PowerDNS

### ISSUE THREAD

**Issue by splk3** [github/octodns#403]
PowerDNS Authoritative Server 4.3.0 added a new "LUA" record type that allows lua-scripted answers to be returned as answers to a DNS query.  For example, a LUA record could respond to an A record request by doing a health check to a server and then returning the properly formatted IP address.

The "LUA" record also is used to implement Geo/Dynamic record types, including multiple health check mechanisms, so the README table can be updated to "Yes" for those features in OctoDNS record type(s) support.

While looking through the [PowerDNS Provider](https://github.com/github/octodns/blob/master/octodns/provider/powerdns.py), it looks like the new record type can be added pretty easily by configuring the LUA record type as another quoted type, leaving the responsibility for format and correctness to the user.

Adding the following should be sufficient (or at least a start):

(not sure if below only update docs or there are other effects)

SUPPORTS_GEO = True
SUPPORTS_DYNAMIC = True 
    SUPPORTS = set(('A', 'AAAA', 'ALIAS', 'CAA', 'CNAME', 'LUA', 'MX', 'NAPTR', 'NS',
                    'PTR', 'SPF', 'SSHFP', 'SRV', 'TXT'))

_data_for_LUA = data_for_quoted
_records_for_LUA = _records_for_quoted

If there is more required, I can look into that, as well.  I'm happy to try and do a pull request, but I have very little python experience and will have to start from scratch getting the development environment set up for testing.

Thanks in advance and having great success with OctoDNS with PowerDNS already!

**Comment by ross** [comment]
Hi @splk3 At a high level octoDNS is focused on providing homogenous support across multiple providers and as such historically hasn't adding support for the special types of records that individual providers offer. The `SUPPORTS` stuff has made that less of a mess than it originally was, but it's still not been something we've looked into/thought about mostly b/c it'll bloat the base/shared parts of things quite a bit over time.

**Comment by splk3** [comment]
@ross - thanks for the quick response.

I totally understand.  I just really like using OctoDNS to manage some of my DNS servers, and sharing changes among team members by having data separate from system/services/etc. has made that really nice.  With GSLB-related things and PowerDNS, I'm stuck using template-based configurations, which aren't nearly as nice in terms of the feedback I can build into the pipelines for testing and implementing changes.

Please let me know what I can do to help determine if this is something that is a possibility to be accepted or not, so I can do a little bit more longer-ish term planning.  Again, I'm more than happy to make the necessary changes, assuming that I am up to it technically.  I certainly don't want to strain the resources of the team for a fringe feature that isn't likely to be used elsewhere any time soon.

**Comment by ross** [comment]
I don't mind it conceptually now that things will generally default to ignoring things they don't understand (and if they don't it's a bug.) Without having put too much thought into it and zero looking into if it'd actually work I think the best option would likely be to give providers a way to dynamically install custom record types that would only apply to them. It'd probably be fun to look into and implement, but given that we don't have a use-case for it internally it's not likely to rise in priority enough for me to dig into implementing it.

**Comment by splk3** [comment]
ok thanks.  I'll look into testing it out myself and see if it is doable.  Worst-case, it's a small change and we can consider whether or not we want to just have a custom provider for our own or keep things as-is.  worth learning the process, in any case.

**Comment by pieterlexis** [comment]
Sorry for necro-bumping this issue. @splk3, did you ever got LUA records working via octoDNS?

**Comment by pieterlexis** [comment]
Another bump, I've added LUA record support here: https://github.com/pieterlexis/octodns/tree/pdns-LUA-record

**Comment by splk3** [comment]
@pieterlexis  - apologies as I've let this sit the whole year.  I'll take a look at your branch.  Thank you for the bump and reminder.

**Comment by splk3** [comment]
@pieterlexis - I've got your branch bootstrapped and working for non-LUA records, but I'm having trouble with the syntax.  Do you have some example entries in the octodns yaml format?  I have a couple of types of LUA records I use frequently that I am going to test, but I assume that the entry is free-form LUA script and they should all work once I've worked out the syntax.  Apologies for being unable to get that figured out myself from the code by itself.

**Comment by pieterlexis** [comment]
here's the syntax:

```yaml
'*.luarecord':
  - type: LUA
    values:
      - lua: "createReverse('%6%')"
        type: 'A'
      - lua: "createReverse6('%33%')"
        type: 'AAAA'
```

**Comment by splk3** [comment]
hi @pieterlexis -
I tested the above on 4.2, 4.3, and 4.4 as best as I could, and I'm getting the following error.  any insights?

I can do a sync to check what would change, and that looks good - when I add --doit to apply the change, it fails.

```
PYTHONPATH=. ./octodns/cmds/sync.py --config-file pdns-auth-vagrant/octodns_vagrant_push_config.yaml --doit
2020-12-04T13:39:06  [140049374238528] INFO  Manager __init__: config_file=pdns-auth-vagrant/octodns_vagrant_push_config.yaml
2020-12-04T13:39:06  [140049374238528] INFO  Manager __init__:   max_workers=1
2020-12-04T13:39:06  [140049374238528] INFO  Manager __init__:   include_meta=False
2020-12-04T13:39:06  [140049374238528] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False
2020-12-04T13:39:06  [140049374238528] INFO  Manager sync:   zone=test.com.
2020-12-04T13:39:06  [140049374238528] INFO  Manager sync:   sources=['config'] -> targets=['powerdns-auth-vagrant']
2020-12-04T13:39:06  [140049374238528] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2020-12-04T13:39:06  [140049374238528] INFO  PowerDnsProvider[powerdns-auth-vagrant] plan: desired=test.com.
2020-12-04T13:39:06  [140049374238528] INFO  PowerDnsProvider[powerdns-auth-vagrant] populate:   found 0 records, exists=False
2020-12-04T13:39:06  [140049374238528] INFO  PowerDnsProvider[powerdns-auth-vagrant] plan:   extra changes
  Create <NsRecord NS 900, test.com., ['ns01.test.com.', 'ns02.test.com.']> (powerdns-auth-vagrant)
2020-12-04T13:39:06  [140049374238528] INFO  PowerDnsProvider[powerdns-auth-vagrant] plan:   Creates=2, Updates=0, Deletes=0, Existing Records=0
2020-12-04T13:39:06  [140049374238528] INFO  Manager 
********************************************************************************
* test.com.
********************************************************************************
* powerdns-auth-vagrant (PowerDnsProvider)
*   Create Zone<test.com.>
*   Create <NsRecord NS 900, test.com., ['ns01.test.com.', 'ns02.test.com.']> (powerdns-auth-vagrant)
*   Create <LuaRecord LUA 3600, *.luarecord.test.com., ['A "createReverse('%6%')"', 'AAAA "createReverse6('%33%')"']> (config)
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
********************************************************************************


2020-12-04T13:39:06  [140049374238528] INFO  PowerDnsProvider[powerdns-auth-vagrant] apply: making changes
Traceback (most recent call last):
  File "./octodns/cmds/sync.py", line 44, in <module>
    main()
  File "./octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "/home/patrick/github/octodns/octodns/manager.py", line 418, in sync
    total_changes += target.apply(plan)
  File "/home/pb/github/octodns/octodns/provider/base.py", line 95, in apply
    self._apply(plan)
  File "/home/patrick/github/octodns/octodns/provider/powerdns.py", line 404, in _apply
    mods.append(getattr(self, '_mod_{}'.format(class_name))(change))
  File "/home/patrick/github/octodns/octodns/provider/powerdns.py", line 346, in _mod_Create
    'records': records_for(new)
  File "/home/patrick/github/octodns/octodns/provider/powerdns.py", line 284, in _records_for_LUA
    return [{
  File "/home/patrick/github/octodns/octodns/provider/powerdns.py", line 285, in <listcomp>
    'content': '{} "{}"'.format(v.rtype, v.lua),
AttributeError: '_LuaValue' object has no attribute 'rtype'
```

**Comment by pieterlexis** [comment]
I messed a variable rename after doing all my testing :(. Should be fixed now. Please fetch and reset. Sorry about that (it really needs tests)

**Comment by splk3** [comment]
> I messed a variable rename after doing all my testing :(. Should be fixed now. Please fetch and reset. Sorry about that (it really needs tests)

@pieterlexis - I tested the latest drop and it works wonderfully.  I've tested LUA-type records, included those snippets in other records, done port and URL-based GSLB records, lookup tables, and free-form LUA statements for custom conditional responses.  

@ross - is there anything we can do to get this merged in?  Any documentation that will be needed or required, or would that wait until the providers are separated into separate repositories?  I'll happily do the documentation at that point to give examples of each record type and how formatting should occur in the <zone>.yaml files for octodns.  I think this might be a good example for provider-specific implementation for other providers than PowerDNS for their custom DNS record types, since they are all a little different.

**Comment by ross** [comment]
> @ross - is there anything we can do to get this merged in? Any documentation that will be needed or required, or would that wait until the providers are separated into separate repositories? I'll happily do the documentation at that point to give examples of each record type and how formatting should occur in the .yaml files for octodns. I think this might be a good example for provider-specific implementation for other providers than PowerDNS for their custom DNS record types, since they are all a little different.

Unfortunately I think this will will need to stay off in a fork until we come up with a clean way to have providers add custom types since the `lua` type would only apply to PowerDNS and wouldn't really belong directly in `records.py`. I had thoughts on what that might look like a while back and I think I can see a path to doing it, but yeah it'll probably be after things move and start being split up. The gist would be some sort of `Record.register` like class method that allows providers to register their custom types. We'd probably need to "namespace" the types with something like `POWERDNS-LUA` so that things wouldn't collide, but otherwise I can see it working...

**Comment by splk3** [comment]
Ok I expected that would be the way things go.  I'll keep an eye on things for an opportunity to claim that namespace and register the new type.  Thanks.

**Comment by ross** [comment]
> Ok I expected that would be the way things go. I'll keep an eye on things for an opportunity to claim that namespace and register the new type. Thanks.

Thanks for the patience/understanding.
