### ISSUE TITLE
invalid state, CNAME cannot coexist with other records

### ISSUE THREAD

**Issue by nothinux** [github/octodns#414]
when I tried sync record from Cloudflare to route53 I get the following error

```
2019-10-15T10:19:02  [139647915988800] INFO  Manager __init__: config_file=./config/production.yaml
2019-10-15T10:19:02  [139647915988800] INFO  Manager __init__:   max_workers=1
2019-10-15T10:19:02  [139647915988800] INFO  Manager __init__:   max_workers=False
2019-10-15T10:19:03  [139647915988800] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False
2019-10-15T10:19:03  [139647915988800] INFO  Manager sync:   zone=dicoding.com.
2019-10-15T10:19:03  [139647915988800] INFO  Manager sync:   sources=['cloudflare'] -> targets=['route53']
Traceback (most recent call last):
  File "/home/taufik/Ops/dns/env/bin/octodns-sync", line 10, in <module>
    sys.exit(main())
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 301, in sync
    plans = [p for f in futures for p in f.result()]
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 224, in _populate_and_plan
    source.populate(zone)
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 277, in populate
    zone.add_record(record, lenient=lenient)
  File "/home/taufik/Ops/dns/env/local/lib/python2.7/site-packages/octodns/zone.py", line 91, in add_record
    .format(record.fqdn))
octodns.zone.InvalidNodeException: Invalid state, CNAME at www.domain.com. cannot coexist with other records
```
how to fix it

**Comment by yzguy** [comment]
Hello,

You can use the `--lenient` flag to attempt to do it. Some providers will allow you to do it, but others won't

Per RFC1034 (https://www.ietf.org/rfc/rfc1034.txt)
> If a CNAME RR is present at a node, no other data should be
present;

https://github.com/github/octodns/blob/8268385af2420e484a509d92763e8045f88b5c56/octodns/zone.py#L85-L91

**Comment by nothinux** [comment]
thanks for your response @yzguy but i get this
```
octodns-sync: error: unrecognized arguments: --lenient
```

**Comment by nothinux** [comment]
in the end i tried to export record from cloudflare and import it to route53

**Comment by yzguy** [comment]
Ah, looks like `--lenient` is only for dump, not syncing. Looks like there is a PR for it: https://github.com/github/octodns/pull/315
