### ISSUE TITLE
octodns.record.ValidationError: Invalid record - missing value

### ISSUE THREAD

**Issue by Juli-BCN** [github/octodns#545]
I have started to received this error for a new domain:
octodns.record.ValidationError: Invalid record www.domain.com. 
- missing value

------------------

$ /octodns/env/bin/octodns-validate --config=/octodns/config/config.yaml
 Traceback (most recent call last):
   File "/octodns/env/bin/octodns-validate", line 8, in <module>
     sys.exit(main())
   File "/octodns/env/lib/python3.8/site-packages/octodns/cmds/validate.py", line 24, in main
     manager.validate_configs()
   File "/octodns/env/lib/python3.8/site-packages/octodns/manager.py", line 427, in validate_configs
     source.populate(zone)
   File "/octodns/env/lib/python3.8/site-packages/octodns/provider/yaml.py", line 152, in populate
     self._populate_from_file(filename, zone, lenient)
   File "/octodns/env/lib/python3.8/site-packages/octodns/provider/yaml.py", line 134, in _populate_from_file
     record = Record.new(zone, name, d, source=self,
   File "/octodns/env/lib/python3.8/site-packages/octodns/record/__init__.py", line 118, in new
     raise ValidationError(fqdn, reasons)
 octodns.record.ValidationError: Invalid record www.domain.com
   - missing value

**Comment by Juli-BCN** [comment]
It stopped happening, not sure if of a change I did
