### ISSUE TITLE
Dyn Invalid name 

### ISSUE THREAD

**Issue by ppieprzycki** [github/octodns#550]
Hi 
I have problem with dump one of my zones. The error that  I get 

```
Traceback (most recent call last):
  File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/bin/octodns-dump", line 9, in <module>
    load_entry_point('octodns==0.9.9', 'console_scripts', 'octodns-dump')()
  File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/lib/python3.5/site-packages/octodns/cmds/dump.py", line 35, in main
    *args.source)
  File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/lib/python3.5/site-packages/octodns/manager.py", line 396, in dump
    source.populate(zone, lenient=lenient)
  File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/lib/python3.5/site-packages/octodns/provider/dyn.py", line 682, in populate
    lenient=lenient)
  File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/lib/python3.5/site-packages/octodns/record/__init__.py", line 118, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record extsip.example.com.
  - invalid name
```

The the entry in dyn looks like following 
"
extsip.example.com

A	30 sec	192.168.192.61
SRV	30 sec	0 1 5061 _sipinternaltls._tcp.example.com.
"

dig for this  entry 
```

;; ANSWER SECTION:
extsip.example.com.   5       IN      A       192.168.192.61
extsip.example.com.   5       IN      SRV     0 1 5061 _sipinternaltls._tcp.example.com.
```

Can you please help with this issue

**Comment by ppieprzycki** [comment]
Sorry seems that this issue is due to validation. I misinterpret the error message. 
I was managed to dump this zone by using the "--lenient" switch.

**Comment by Juli-BCN** [comment]
Piotr, I am having the very same issue with with a record that is SRV and TXT. I can add the TXT, but no chance to add the other one, not even on its own. It is the last record of my domain before going live :D Any tip?

**Comment by ppieprzycki** [comment]
@Juli-BCN  
Hi, In case the main issue was with the entry name.  According to RFC for the SRV record name should start with underscore   https://www.ietf.org/rfc/rfc2782.txt.
I was able to get rid of such entries in my zones so do not have issues with sync. 
For dump already existing zone --lenient option was sufficient. 


Regards

**Comment by ross** [comment]
Fwiw you can preserve and manage non-compliant records by disabling strict checking on a per-record basis with `octodns.lenient=True`, e.g.

```yaml
foo.invalid._tcp:
  octodns:
    lenient: true
  ttl: 1800
  type: SRV
  values:
    - port: 443
      priority: 0
      target: foo.bar.com.
      weight: 0
...
```
