### ISSUE TITLE
UltraDNS dump  zone 

### ISSUE THREAD

**Issue by ppieprzycki** [github/octodns#593]
Hi have an issue with the ultradns provider and octodns-dump 
This is new provider in master branch https://github.com/github/octodns/pull/579

@phelpsw  Maybe you can check whether dump is working in your environment.

`
octodns-dump --config=octo-ultra.conf --output-dir=tmp5/ example.zone. ultra --debug

2020-07-31T21:39:47  [139762935260736] DEBUG UltraProvider[ultra] _request: method=POST, path=/v2/authorization/token
2020-07-31T21:39:47  [139762935260736] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): restapi.ultradns.com:443
2020-07-31T21:39:49  [139762935260736] DEBUG urllib3.connectionpool https://restapi.ultradns.com:443 "POST /v2/authorization/token HTTP/1.1" 200 314
2020-07-31T21:39:49  [139762935260736] DEBUG UltraProvider[ultra] _request:   status=200
Traceback (most recent call last):
  File "/home/user/aaa/bin/octodns-dump", line 11, in <module>
    load_entry_point('octodns==0.9.10', 'console_scripts', 'octodns-dump')()
  File "/home/user/aaa/lib64/python3.6/site-packages/octodns/cmds/dump.py", line 33, in main
    manager = Manager(args.config_file)
  File "/home/user/aaa/lib64/python3.6/site-packages/octodns/manager.py", line 125, in __init__
    for name in sorted(self.config['zones'].keys(), key=lambda s: s[::-1]):
KeyError: 'zones'
`

**Comment by ross** [comment]
> KeyError: 'zones'

That seems to indicate that the `zones` key is missing from `octo-ultra.conf`

**Comment by ppieprzycki** [comment]
@ross  Thank you for this hint. 
Indeed even if I use octodns-dump only I need to declare at least one zone in the config file.

I'm closing it.
