### ISSUE TITLE
Cloudflare Invalid Request Headers

### ISSUE THREAD

**Issue by Muirrum** [github/octodns#595]
Attempting to update the DNS through cloudflare (even noop) results in the following error:
```
Traceback (most recent call last):
  File "/home/osalter/.local/bin/octodns-sync", line 33, in <module>
    sys.exit(load_entry_point('octodns==0.9.10', 'console_scripts', 'octodns-sync')())
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_targets=args.target,
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/manager.py", line 315, in sync
    plans = [p for f in futures for p in f.result()]
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/manager.py", line 315, in <listcomp>
    plans = [p for f in futures for p in f.result()]
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/manager.py", line 243, in _populate_and_plan
    plan = target.plan(zone)
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/provider/base.py", line 51, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 261, in populate
    records = self.zone_records(zone)
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 214, in zone_records
    zone_id = self.zones.get(zone.name, False)
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 114, in zones
    resp = self._request('GET', '/zones', params={'page': page})
  File "/home/osalter/.local/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 101, in _request
    raise CloudflareError(resp.json())
octodns.provider.cloudflare.CloudflareError: Invalid request headers
```

**Comment by Muirrum** [comment]
Was using wrong API key
