### ISSUE TITLE
Route53 API Rate Exceeded

### ISSUE THREAD

**Issue by dolvany** [github/octodns#96]
API rate is exceeded when syncing 514 zones.

botocore.exceptions.ClientError: An error occurred (Throttling) when calling the ListResourceRecordSets operation (reached max retries: 4): Rate exceeded

**Comment by ross** [comment]
If you have one handy, a full stack trace would be nice to have here to make sure that I can recreate the test case as closely as possible as I'm probably not going to manage to hit that limit myself.

**Comment by dolvany** [comment]
Traceback (most recent call last):
File "/usr/bin/octodns-sync", line 9, in <module>
load_entry_point('octodns==0.8.5', 'console_scripts', 'octodns-sync')()
File "/usr/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
dry_run=not args.doit, force=args.force)
File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 260, in sync
plans = [p for f in futures for p in f.result()]
File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 49, in result
return self.func(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/octodns/manager.py", line 196, in _populate_and_plan
plan = target.plan(zone)
File "/usr/lib/python2.7/site-packages/octodns/provider/base.py", line 107, in plan
self.populate(existing, target=True, lenient=True)
File "/usr/lib/python2.7/site-packages/octodns/provider/route53.py", line 431, in populate
for rrset in self._load_records(zone_id):
File "/usr/lib/python2.7/site-packages/octodns/provider/route53.py", line 404, in _load_records
**start)
File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the ListResourceRecordSets operation (reached max retries: 4): Rate exceeded

**Comment by dolvany** [comment]
Hmm, it doesn't happen on every run. Just some runs.

**Comment by ross** [comment]
> Hmm, it doesn't happen on every run. Just some runs.

Yeah, probably just the details of their rate limiting implementation. Would be surprised if it's a fuzzy limits based on implementation details/simplifications. 

Thanks for the stack trace. I'll try and take a look at this over the weekend.

**Comment by dolvany** [comment]
No way, man. It's miller time!
